services:
  ingest-orquestator-server:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    environment:
      INGEST_DOCLING_ACCELERATOR_DEVICE: cuda
      INGEST_DOCLING_NUM_THREADS: 8
      INGEST_DOCLING_CUDA_USE_FLASH_ATTENTION2: "false"
      INGEST_DOCLING_ALLOW_EXTERNAL_PLUGINS: "true"
      INGEST_DOCLING_PDF_OCR_ENGINE: suryaocr
      INGEST_DOCLING_PDF_OCR_USE_GPU: "true"
      INGEST_DOCLING_PDF_LAYOUT_MODEL: docling-layout-heron-101
      INGEST_DOCLING_PDF_TABLE_STRUCTURE_BACKEND: tableformer
      INGEST_DOCLING_PDF_PICTURE_CLASSIFIER_PRESET: document_figure_classifier_v2
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
